[DEFAULT]
audio_file = 
whisper_model = large-v3-turbo
#whisper_model = large-v2
output_dir = ~/Downloads
use_mlx = true
force_cpu = false
hf_token_file = .hf_token
language = en
#language = yue
task = transcribe

# Context to help the model (vocabulary, punctuation style, subject matter)
#initial_prompt = Transcribe lecture. Use proper punctuation, capitalization, and sentence structure. Ignore echoes, stuttering, and repetitions.

initial_prompt = 以下是廣東話講座的內容。請使用繁體中文，並加上適當的標點符號。忽略回音、口吃和重複。

enable_chunking = false
chunk_length = 120
overlap_length = 10
max_segment_length = 1000
verbose_output = false